### ISSUE TITLE
"NOT using graph editor observer No module named grapheditor" with both test_light.py and test_light_interception.py

### ISSUE THREAD

**Issue by Illustratien** [openalea-incubator/WALTer#90]
Hi,

I went through steps from this [wiki page](https://github.com/openalea-incubator/WALTer/wiki/install)
```
conda create -n walter -c openalea openalea.lpy boost=1.66
activate walter
conda install -c openalea -c conda-forge pvlib-python pytables alinea.astk
conda install -c openalea openalea.mtg alinea.caribu notebook matplotlib pandas scipy
```
Then  I went to the cloning directory to run setup.py 
```
cd C:/Users/twang/Documents/GitHub/WALTer
python setup.py install
```
Here I got the warnings:
```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
```
When I run `test_light.py` and `test_light_interception.py`

I got the following message
```
NOT using graph editor observer No module named grapheditor
```
I have tried the lines mentioned in this [thread](https://github.com/openalea/lpy/issues/12)  but the meassage is still there.

Is this meassage cause a problem for running the project.
 
And is this message related to the warnings during the installation of setup.py?

Thank you in advanced.

Here is some basic inofromation about my working system.
```
          conda version : 4.7.10
    conda-build version : 3.17.8
         python version : 2.7.16.final.0
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/2.7.16 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by pradal** [comment]
The warning is normal. Do not worry. 
Moreover, when you exec test_light.py, you don not run it, but just the import.
To test it, install nosetests (```conda install nose```) and run it using the command `nosetests`

**Comment by Illustratien** [comment]
Thanks @pradal ,
I got some new error after nose tests.
Here is what I did:

```
conda install nose
cd C:/Users/twang/Documents/GitHub/WALTer/test
nosetest
```
The first part of error message.

```
Use Project test_one_sim located at C:\Users\twang\Documents\GitHub\WALTer\test\test_one_sim
NOT using graph editor observer No module named grapheditor
ce qu'on ecrit: 0

The Fitness could not be computed because CARIBU_state = disabled or the model has not run for enough days

Aloha
Au revoir
The Fitness could not be computed because CARIBU_state = disabled or the model has not run for enough days
.Use Project test_multi_sim located at C:\Users\twang\Documents\GitHub\WALTer\test\test_multi_sim
Multiple processes
generate ids
run simulations
Use Project test_multi_sim located at C:\Users\twang\Documents\GitHub\WALTer\test\test_multi_sim
Use Project test_multi_sim located at C:\Users\twang\Documents\GitHub\WALTer\test\test_multi_sim
Use Project test_multi_sim located at C:\Users\twang\Documents\GitHub\WALTer\test\test_multi_sim
NOT using graph editor observer No module named grapheditor
NOT using graph editor observer No module named grapheditor
NOT using graph editor observer No module named grapheditor
ce qu'on ecrit: 0
ce qu'on ecrit: 0
```
and after some more messages...
```
Aloha
Au revoir
Au revoir
The Fitness could not be computed because CARIBU_state = disabled or the model has not run for enough days
The Fitness could not be computed because CARIBU_state = disabled or the model has not run for enough days
Au revoir
The Fitness could not be computed because CARIBU_state = disabled or the model has not run for enough days
.Use Project combi_params_error located at C:\Users\twang\Documents\GitHub\WALTer\test\combi_params_error
Multiple processes
generate ids
run simulations
Use Project combi_params_error located at C:\Users\twang\Documents\GitHub\WALTer\test\combi_params_error
Use Project combi_params_error located at C:\Users\twang\Documents\GitHub\WALTer\test\combi_params_error
NOT using graph editor observer No module named grapheditor
NOT using graph editor observer No module named grapheditor
ce qu'on ecrit: 0
```
The error for 

`test.test_light.test_get_turtle_light`,` test.test_light_interception.test_zero_light`,  `test.test_light_interception.test_shift_in_light`, `test if total par intercepted is above or below incident par`,`test.test_no_regression.test_same_result`are all very similar.

```
ERROR: test.test_light.test_get_turtle_light
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\twang\Miniconda2\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\twang\Documents\GitHub\WALTer\test\test_light.py", line 21, in test_get_turtle_light
    nrj, dir = zip(*get_turtle_light(par))
  File "C:\Users\twang\Documents\GitHub\WALTer\src\walter\light.py", line 61, in get_turtle_light
    daydate=daydate, longitude = longitude, latitude=latitude, altitude=altitude, timezone=timezone)
TypeError: sky_sources() got an unexpected keyword argument 'turtle_sectors'
```


and the final message.
```
Ran 30 tests in 77.141s

FAILED (errors=5)
```

**Comment by pradal** [comment]
Dear @Illustratien 
Have you solve this issue? Do you need our help?
I may work on it with @christian34 
Cheers
Christophe

**Comment by Illustratien** [comment]
Dear @pradal  
Thank you for your reply.
I need your help very much.

I don't know how to check whether I successfuly installed or not.
And I don't know hot to use it.

Can you give me some guide line to use WALTer?
(ie., some reproducible examples, input data requirements)
 
Cheers
Tien-Cheng
